#-------------------------------------------------
                  #VITAL LENS
#-------------------------------------------------

# Language change: En (INGLES) // Es (ESPAÑOL)
language: "en"

health-bar:

  # Enable or disable the health being shown as a number next to the health bar.
  show-numbers: true

  # Change the style of the health bar, available options:
  # default // grapes // orion // masaru // inari // valencho // nixcel // crisneko
  style: default

  # The icon that will be used for the health bar.
  heart-symbol: "❤"

  # Width of the entity health bar.
  width: 120

mob-type-icon:

  # Shows a legend for HOSTILE // PEACEFUL // NEUTRAL entities next to the bar.
  enable: false
