#-------------------------------------------------
                  #VITAL LENS
#-------------------------------------------------

language: "en"

health-bar:

  #activa o desactiva los numeros de la vida
  show-numbers: true

  #añade un estilo para la barra de vida
  # default // grapes // orion // masaru // inari // valencho // nixcel // crisneko
  style: default

  #simbolo para la vida
  heart-symbol: "❤"

  #ancho del texto de la vida de las entidades
  width: 120

mob-type-icon:

  #muestra un indicador de HOSTIL // PACIFICO // NEUTRAL de las entidades
  enable: false
